steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/openaiservice', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/openaiservice' ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'openaiservice'
      - '--image=gcr.io/$PROJECT_ID/openaiservice'
      - '--platform=managed'
      - '--region=us-east1'
      - '--allow-unauthenticated'
      - '--set-secrets=OPENAI_API_KEY=OPENAI_API_KEY:latest'
      - '--set-env-vars=PORT=8080'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300s'
      - '--max-instances=3'
      - '--min-instances=0'
